version: "3.9"

services:
  backend:
    image: turtle.shareyourhealth.cn:v0.0.1
    environment:
      DATABASE_URL: sqlite:////app/data/app.db
    volumes:
      - ./backend:/app/backend
      - ../volume/data:/app/data
    ports:
      - "9380:8000"
    working_dir: /app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
